# Basic Site Settings
locale                   : "en-US"
title                    : "Efe Öztaban - Academic Portfolio"
title_separator          : "-"
name                     : &name "Efe Öztaban"
description              : &description "Graduate Researcher in High Energy Astrophysics and Machine Learning Enthusiast"
url                      : "https://efeoztaban.com"
baseurl                  : "" 
repository               : "efeoztaban/efeoztaban.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Efe Öztaban"
  pronouns         : "he/him"  
  bio              : "Graduate researcher specializing in machine learning applications for high energy astrophysics."
  location         : "Istanbul, Turkey"
  employer         : "Sabancı University"
  uri              : "https://efeoztaban.com"
  email            : "efeoztaban@sabanciuniv.edu" 

  # Academic websites
  arxiv            : "https://arxiv.org/search/?searchtype=author&query=Oztaban%2C+E"
  googlescholar    : "https://scholar.google.com/citations?user=Uitk20oAAAAJ"
  orcid            : "https://orcid.org/0000-0000-0000-0000" # Update with your actual ORCID
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=Oztaban+E"

  # Repositories and software development
  github           : "efeoztaban"
  kaggle           : "efeoztaban"  
  stackoverflow    : "123456/efeoztaban" # Replace with your actual Stack Overflow ID

  # Social media
  linkedin         : "efe-oztaban"
  twitter          : "efeoztaban" 
  instagram        : "efeoztaban"
  youtube          : "EfeÖztaban"

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   : "default-teaser.png"
breadcrumbs              : true 
words_per_minute         : 160
future                   : true
read_more                : "enabled"
talkmap_link             : true
comments:
  provider               : "disqus"
  disqus:
    shortname            : "efeoztaban"

# Analytics
analytics:
  provider               : "google-analytics-4"
  google:
    tracking_id          : "UA-XXXXXXXXX-X" # Replace with your Google Analytics ID

# Social Sharing
twitter:
  username               : "efeoztaban"
facebook:
  username               : "efeoztaban"
og_image                 : "images/default-social.png"

# Reading Files
include:
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .sass-cache
  - node_modules
  - tmp

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: Europe/Istanbul

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
